name: Ejemplo_edwin # Cambiar

on:
    push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Instalar Python 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Proceso python # Cambiar nombre
      run: |

        python Ejemplo.py      

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Ejemplo_edwin" # Ejemplo
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: pinedaedwin90@yahopo.com # Correo
        commit_author: DataIntelligence BOT <pinedaedwin90@yahopo.com> # Correo
        push_options: '--force'